int _isupper(int c);
int _isdigit(int c);
int _putchar(char c);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void jack_bauer(void);
void times_table(void);
int mul(int a, int b);
void print_to_98(int n);
void print_times_table(int n);
